<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'mautics',
	'db_user' => 'root',
	'db_password' => 'password',
	'db_backup_tables' => 1,
	'db_backup_prefix' => 'bak_',
	'mailer_from_name' => 'admin admin',
	'mailer_from_email' => 'aminsaki69@gmail.com',
	'mailer_transport' => 'smtp',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_amazon_region' => 'us-east-1',
	'mailer_amazon_other_region' => null,
	'mailer_api_key' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/../var/spool',
	'secret_key' => '0224e2877b68621bcaf1406bdbe8691850be0648f90a0cb7d3a997488662fc5a',
	'site_url' => 'http://86.104.39.173/index.php',
);
